# Generated by Django 3.2 on 2022-06-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户数据', 'verbose_name_plural': '用户数据'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nike_name',
            field=models.CharField(blank=True, default='', max_length=23, verbose_name='昵称'),
        ),
    ]
